### ISSUE TITLE
poop

### ISSUE THREAD

**Issue by NirvanaNevermind** [Thaiteum/9b9t.news#1]

**Comment by NirvanaNevermind** [comment]
![image](https://user-images.githubusercontent.com/73959575/108727053-06e4e700-7520-11eb-9e12-72ee8e6db7e0.png)

**Comment by veryepicgamer69** [comment]
if you have a problem with your poop, sorry but i can't really help you. if you have intense diarheea or heavy constipation please seek a doctor.

**Comment by NirvanaNevermind** [comment]
i don't feel this is fixed, you addressed a different issue

**Comment by veryepicgamer69** [comment]
you said "poop", that is all i know about this subject. please do not rape me mr nirvana

**Comment by SpicyBigGithub** [comment]
k
